### ISSUE TITLE
Little note to the anonymous mlix8hoblc 

### ISSUE THREAD

**Issue by CrazyWolf13** [CrazyWolf13/installer#1]
That wrote this nice letter to my inbox:

I'm not sure why you are watching my so hard, and how this commit found it's way to you, but probably it's fun for you.
![grafik](https://github.com/CrazyWolf13/installer/assets/96661824/53f9e273-4af9-4d2f-af69-9e09616cb04d)

I'm always to improve myself, but this script and also many more from my current repositorys are not related to any work content, so will never hit any real production.

To this script specifically: 
This was just a qick and dirty installer, intended to programatically make it easier to install windows and all my configurations.

Also this script won't run anymore than like 5-10 times, and care less for such s script not to have crazy functions and structuring.

If you have any intentions on giving any real advice instead of just being a random dick on the internet and watching like a little creep, I strongly suggest to go see some sunlight, and stop watching me, there is nothing to see here :) .

If you intent to give me any suggestions, feel free to share your matrix username and I'll contact you, so we may have a normal conversation, instead of this childish communication via delete commit messages.

**Comment by kitsudaiki** [comment]
I also had such stupid comment of this mlix8hoblc in my inbox today. The comment had a different text, but basically the same content and aggressive insults. Based on some claims in the text, the person did never read the code and only wants to provoke. 
Even there are some hints left in github about this mlix8hoblc, the account itself seems to be deleted. Maybe this person did never got a job as software developer or was a victim of such feedback at work and was now so frustrated, that he/she wrote such comments in a blind rage in some random repositories, before rage quit from github.
I think your code was also never read by mlix8hoblc, so don't think too hard about it and don't expect any constructive feedback from this person. 
Keep going with your work and don't let yourself get hurt by such comments!

**Comment by CrazyWolf13** [comment]
Oh gosh, really appreciate your response, how'd you find this so quickly?

Yeah I came to a similar conclusion, he worked on quite some projects, but his accounts seems to have been deleted or blocked.

Yeah I was a bit shocked as I read it, as yeah I am a young developer and self taught, so those words quite hit me a bit.
Huge thanks for your kind words 🫶

**Comment by manojscoder** [comment]
I also got this stupid mail from mlix8hoblc in my inbox today.

**Comment by CrazyWolf13** [comment]
@kitsudaiki I've made a little post on reddit: https://www.reddit.com/r/github/comments/1dy3pxb/ignore_comments_from_mlix8hoblc/

Hopefully more people see this.

**Comment by CrazyWolf13** [comment]
@manojscoder Thanks for confirming :)

**Comment by PaulineFranck98** [comment]
Hey! I also received a message from this person yesterday. It is very painful to receive so much hate, because I only started learning to code six months ago, and I know I need to improve myself, but reading this kind of message is very discouraging and hurtful. Thank you for posting this message, it reassures me nonetheless. Good luck to you, keep learning and exploring, and don't let anyone put you down!

**Comment by gros-pataplouf** [comment]
Hi, same here. The hatemail arrived 4 minutes after the commit, maybe it's partly automated (at least the retrieval of random repos with recent commits). Anyway, let's NOT feed the troll.
